openapi: 3.1.0
info:
  title: FireFly Controller
  description: Configure and manage controllers and client configurations
  version: 2024.6.1
servers:
  - url: http://{domain}
    variables:
      domain:
        default: 192.168.10.101
        description: IP address of the device's ethernet interface
tags:
  - name: Authorization
    description: Mangage long-term http authorizations
  - name: Event and Error Logs
    description: Operations for the event and error logs
  - name: Version
    description: Operations for the hardware and firmware versions
  - name: Certificates
    description: Operations for the storage, retrieval, and management of certificates
  - name: Configuration
    description: Operations for configuring various services on both controllers and clients
  - name: High Voltage
    description: Operations for configuring high voltage devices
  - name: Controllers
    description: Mangage controllers
  - name: Clients
    description: Mangage Clients

##########################################################
## NOTE: This may not render except in the next-gen     ##
## Swagger UI renderer https://editor-next.swagger.io/  ##
##########################################################

paths:


##########################################################
## Version                                              ##
##########################################################
  
  /api/version:
    get:
      tags:
        - Version
      summary: Hardware and firmware version information
      description: Retrieves the hardware and firmware version information
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/applicationVersionInfo'
  /ui/version:
    get:
      tags:
        - Version
      summary: User interface version information
      description: Retrieves the user interface version information
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/uiVersionInfo'
        '404':
          description: File system failure


##########################################################
## Events and Errors                                    ##
##########################################################
  
  /api/errors:
    get:
      tags:
        - Event and Error Logs
      summary: Error log information
      description: Retrieve all of the active errors
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorLog'
              examples:
                Events in the log:
                  $ref: '#/components/examples/errorLog'
                No log entries:
                  $ref: '#/components/examples/emptyArray'
  /api/events:
    get:
      tags:
        - Event and Error Logs
      summary: Event log information
      description: Retrieve all of the events still remaining in the event log
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/eventLog'
              examples:
                Events in the log:
                  $ref: '#/components/examples/eventLog'
                No log entries:
                  $ref: '#/components/examples/emptyArray'


##########################################################
## OTA Firmware                                         ##
##########################################################
  
  /api/ota:
    post:
      tags:
        - Configuration
      summary: OTA firmware configuration
      description: Stores the over-the-air (OTA) firmware configuration
      security:
        - visualToken: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/otaConfiguration'
            examples:
                http:
                  $ref: '#/components/examples/ota_http'
                https:
                  $ref: '#/components/examples/ota_https'
      responses:
        '201':
          description: Created
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/bad_request_message'
              examples:
                Missing body:
                  value:
                    message: Request requires body
                Missing certificate field for on https:
                  value:
                    message: https requires certificate
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/bad_request_message'
              example:
                message: Configuration already exists
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_message'
              example:
                message: File system not mounted
    get:
      tags:
        - Configuration
      summary: OTA firmware configuration
      description: Retrieve the over-the-air (OTA) firmware configuration
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/otaConfiguration'
              examples:
                http:
                  $ref: '#/components/examples/ota_http'
                https:
                  $ref: '#/components/examples/ota_https'
        '404':
          description: No configuration exists
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_message'
              example:
                message: File system not mounted
    delete:
      tags:
        - Configuration
      summary: OTA firmware configuration
      description: Delete the over-the-air (OTA) firmware configuration
      security:
        - visualToken: []
      responses:
        '204':
          description: Deleted configuration successfully
        '401':
          description: Unauthorized
        '404':
          description: No configuration exists
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_message'
              example:
                message: File system not mounted

  /api/ota/app:
    post:
      tags:
        - Configuration
      summary: Force application OTA update
      description: Forces an over-the-air (OTA) application firmware retrieval with the URL provided
      security:
        - visualToken: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/forceOTAConfiguration'
            examples:
              http:
                value:
                  url: http://www.somewhere.com/firmware.bin
              https:
                value:
                  url: https://www.somewhere.com/firmware.bin
                  certificate: mycert.pem
      responses:
        '202':
          description: Request accepted
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/bad_request_message'
        '401':
          description: Unauthorized

  /api/ota/spiffs:
    post:
      tags:
        - Configuration
      summary: Force SPIFFs OTA update
      description: Forces an over-the-air (OTA) SPIFFs retrieval with the URL provided
      security:
        - visualToken: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/forceOTAConfiguration'
            examples:
              http:
                value:
                  url: http://www.somewhere.com/spiffs.bin
              https:
                value:
                  url: https://www.somewhere.com/spiffs.bin
                  certificate: mycert.pem
      responses:
        '202':
          description: Request accepted
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/bad_request_message'
        '401':
          description: Unauthorized


##########################################################
## Certificates                                         ##
##########################################################

  /certs:
    get:
      tags:
        - Certificates
      summary: Get certificate list
      description: Retrives the list of certificates in flash storage
      security:
        - visualToken: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/certificateList'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_message'
              example:
                message: File system not mounted
    post:
      tags:
        - Certificates
      summary: Create a new certificate
      description: Creates a new certificate with the content in the payload
      security:
        - visualToken: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '201':
          description: Created
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/bad_request_message'
              example:
                message: Filename must be 31 characters or less
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/bad_request_message'
              example:
                message: Certificate already exists
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_message'
              example:
                message: File system not mounted

  /certs/{filename}:
    get:
      tags:
        - Certificates
      summary: Get a certificate
      description: Retrieves the content of a certificate
      security:
        - visualToken: []
      parameters:
        - in: path
          name: filename
          schema:
            type: string
            example: mycert.pem
            maxLength: 31
          required: true
          description: Certificate filename to retrieve
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/certificateContent'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/bad_request_message'
              example:
                message: Filename must be 31 characters or less
        '401':
          description: Unauthorized
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_message'
              example:
                message: File system not mounted
    delete:
      tags:
        - Certificates
      summary: Delete a certificate
      description: Deletes the requested certificate from flash storage
      security:
        - visualToken: []
      parameters:
        - in: path
          name: file
          schema:
            type: string
            example: mycert.pem
            maxLength: 31
          required: true
          description: Certificate filename to delete
      responses:
        '204':
          description: Deleted certificate successfully
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/bad_request_message'
              example:
                message: Filename must be 31 characters or less
        '401':
          description: Unauthorized
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_message'
              example:
                message: File system not mounted
  /auth:
    post:
      tags:
        - Authorization
      summary: Authorize the visual token
      description: Creates a long-term authorization for a visual token (typically 60 minutes)
      security:
        - visualToken: []
      responses:
        '204':
          description: Authorized
        '401':
          description: Unauthorized

  /api/breakers:
    get:
      tags:
        - High Voltage
      summary: Retrieve a list of breakers defined
      description: Retrieves a list of all breakers defined
      security:
        - visualToken: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/breaker'
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_message'
              example:
                message: File system not mounted
    post:
      tags:
        - High Voltage
      summary: Create a new breaker
      description: Create a new high-voltage breaker
      security:
        - visualToken: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/breaker'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/uniqueId'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/bad_request_message'
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_message'
              example:
                message: File system not mounted

  /api/breakers/{id}:
##########################################################
## Provisioning                                         ##
##########################################################

    get:
      tags:
        - High Voltage
      summary: Retrieve a breaker by ID
      description: Retrieve a specific breaker by assigned ID
      security:
        - visualToken: []
      parameters:
        - in: path
          name: id
          schema:
            type: integer
            example: 9
          required: true
          description: Breaker ID to retrieve
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/breaker'
        '401':
          description: Unauthorized
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_message'
              example:
                message: File system not mounted
    put:
      tags:
        - High Voltage
      summary: Update a breaker
      description: Updates the existing breaker
      security:
        - visualToken: []
      parameters:
        - in: path
          name: id
          schema:
            type: integer
            example: 9
          required: true
          description: Breaker ID to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/breaker'
      responses:
        '204':
          description: Success
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/bad_request_message'
        '401':
          description: Unauthorized
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_message'
              example:
                message: File system not mounted
    delete:
      tags:
        - High Voltage
      summary: Create a new breaker
      description: Create a new high-voltage breaker
      security:
        - visualToken: []
      parameters:
        - in: path
          name: id
          schema:
            type: integer
            example: 9
          required: true
          description: Breaker ID to delete
      responses:
        '204':
          description: Success
        '401':
          description: Unauthorized
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_message'
              example:
                message: File system not mounted
  
  /api/relays:
    get:
      tags:
        - High Voltage
      summary: Retrieve a list of relays defined
      description: Retrieves a list of all relays defined
      security:
        - visualToken: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/relay'
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_message'
              example:
                message: File system not mounted
    post:
      tags:
        - High Voltage
      summary: Create a new relay
      description: Create a new high-voltage relay
      security:
        - visualToken: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/relay'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/uniqueId'
              example:
                id: 4
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/bad_request_message'
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_message'
              example:
                message: File system not mounted

  /api/relays/{id}:

##########################################################
## High Voltage                                         ##
##########################################################

    get:
      tags:
        - High Voltage
      summary: Retrieve a relay by ID
      description: Retrieve a specific relay by assigned ID
      security:
        - visualToken: []
      parameters:
        - in: path
          name: id
          schema:
            type: integer
            example: 4
          required: true
          description: Relay ID to retrieve
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/relay'
        '401':
          description: Unauthorized
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_message'
              example:
                message: File system not mounted
    put:
      tags:
        - High Voltage
      summary: Update a relay
      description: Updates the existing relay
      security:
        - visualToken: []
      parameters:
        - in: path
          name: id
          schema:
            type: integer
            example: 4
          required: true
          description: Relay ID to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/relay'
      responses:
        '204':
          description: Success
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/bad_request_message'
        '401':
          description: Unauthorized
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_message'
              example:
                message: File system not mounted
    delete:
      tags:
        - High Voltage
      summary: Create a new relay
      description: Create a new high-voltage relay
      security:
        - visualToken: []
      parameters:
        - in: path
          name: id
          schema:
            type: integer
            example: 4
          required: true
          description: Relay ID to delete
      responses:
        '204':
          description: Success
        '401':
          description: Unauthorized
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_message'
              example:
                message: File system not mounted

  /api/controllers:
    get:
      tags:
        - Controllers
      summary: Retrieve a list of controllers defined
      description: Retrieves a list of all controllers defined
      security:
        - visualToken: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/controller'
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_message'
              example:
                message: File system not mounted
    post:
      tags:
        - Controllers
      summary: Create a new controller
      description: Create a new controller
      security:
        - visualToken: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/controller'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/uniqueId'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/bad_request_message'
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_message'
              example:
                message: File system not mounted

  /api/controllers/{id}:
    patch:
      tags:
        - Controllers
      summary: Update an existing controller
      description: Updates an existing controller
      security:
        - visualToken: []
      parameters:
        - in: path
          name: id
          schema:
            type: integer
            example: 9
          required: true
          description: Controller ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/controller'
      responses:
        '204':
          description: Success
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/bad_request_message'
        '401':
          description: Unauthorized
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_message'
              example:
                message: File system not mounted

  /api/controllers/{id}/inputs:
    get:
      tags:
        - Controllers
      summary: Retrieve list of controller inputs
      description: Retrieve list of all of the inputs for the requested controller
      security:
        - visualToken: []
      parameters:
        - in: path
          name: id
          schema:
            type: integer
            example: 9
          required: true
          description: Controller ID to retrieve
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/inputPort'
        '401':
          description: Unauthorized
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_message'
              example:
                message: File system not mounted

  /api/controllers/{id}/inputs/{port}:
    get:
      tags:
        - Controllers
      summary: Retrieve input port
      description: Retrieve the requested input port information for the requested controller
      security:
        - visualToken: []
      parameters:
        - in: path
          name: id
          schema:
            type: integer
            example: 9
          required: true
          description: Controller ID to retrieve
        - in: path
          name: port
          schema:
            type: integer
            example: 12
          required: true
          description: Port number to retrieve
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inputPort'
        '401':
          description: Unauthorized
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_message'
              example:
                message: File system not mounted
    put:
      tags:
        - Controllers
      summary: Update a port
      description: Update a port
      security:
        - visualToken: []
      parameters:
        - in: path
          name: id
          schema:
            type: integer
            example: 9
          required: true
          description: Controller ID to update
        - in: path
          name: port
          schema:
            type: integer
            example: 12
          required: true
          description: Port number to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/inputPort'
      responses:
        '204':
          description: Success
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/bad_request_message'
        '401':
          description: Unauthorized
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_message'
              example:
                message: File system not mounted
##########################################################
## Controllers                                          ##
##########################################################

  /api/controllers/{id}/inputs/{port}/channels:
    get:
      tags:
        - Controllers
      summary: Retrieve input port channel
      description: Retrieve the requested input port channel information for the requested controller
      security:
        - visualToken: []
      parameters:
        - in: path
          name: id
          schema:
            type: integer
            example: 9
          required: true
          description: Controller ID to retrieve
        - in: path
          name: port
          schema:
            type: integer
            example: 12
          required: true
          description: Port number to retrieve
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/channel'
        '401':
          description: Unauthorized
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_message'
              example:
                message: File system not mounted


  /api/controllers/{id}/inputs/{port}/channels/{channel}:
    get:
      tags:
        - Controllers
      summary: Retrieve input port channel
      description: Retrieve the requested input port channel information for the requested controller
      security:
        - visualToken: []
      parameters:
        - in: path
          name: id
          schema:
            type: integer
            example: 9
          required: true
          description: Controller ID to retrieve
        - in: path
          name: port
          schema:
            type: integer
            example: 12
          required: true
          description: Port number to retrieve
        - in: path
          name: channel
          schema:
            type: integer
            example: 2
          required: true
          description: Channel number to retrieve
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/channel'
        '401':
          description: Unauthorized
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_message'
              example:
                message: File system not mounted
    post:
      tags:
        - Controllers
      summary: Create a channel configuration override
      description: Creates a port's channel configuration override
      security:
        - visualToken: []
      parameters:
        - in: path
          name: id
          schema:
            type: integer
            example: 9
          required: true
          description: Controller ID
        - in: path
          name: port
          schema:
            type: integer
            example: 12
          required: true
          description: Port number
        - in: path
          name: channel
          schema:
            type: integer
            example: 2
          required: true
          description: Channel number to create the override
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/channel'
      responses:
        '204':
          description: Success
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/bad_request_message'
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_message'
              example:
                message: File system not mounted

    delete:
      tags:
        - Controllers
      summary: Delete a channel configuration override
      description: Deletes the port's channel configuration and returns it to the default configuration
      security:
        - visualToken: []
      parameters:
        - in: path
          name: id
          schema:
            type: integer
            example: 9
          required: true
          description: Controller ID
        - in: path
          name: port
          schema:
            type: integer
            example: 12
          required: true
          description: Port number
        - in: path
          name: channel
          schema:
            type: integer
            example: 2
          required: true
          description: Channel number to delete the override
      responses:
        '204':
          description: Deleted channel configuration successfully
        '401':
          description: Unauthorized
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_message'
              example:
                message: File system not mounted

  
##########################################################
##########################################################
## Components                                           ##
##########################################################
##########################################################

components:

##########################################################
## Security                                             ##
##########################################################

  securitySchemes:
    visualToken:
      type: apiKey
      in: header
      name: visual-token
      description: A security token visually displayed on the device which changes on a regular basis

 
  schemas:

    ##########################################################
    ## Standard API Responses                               ##
    ##########################################################

    error_message:
      type: object
      properties:
        error:
          type: string
          description: Message describing the error condition
          example: Unexpected Error
    bad_request_message:
      type: object
      properties:
        message:
          type: string
          description: Message describing the issue with the request body
          example: Missing parameter in request
    networkInterfaceTypes:
      type: string
      enum:
        - bluetooth
        - ethernet
        - wifi
        - wifi_ap


    ##########################################################
    ## Errors and Event Log                                 ##
    ##########################################################

    eventLog:
      type: array
      items:
        $ref: '#/components/schemas/eventLogEntry'

    eventLogEntry:
      type: object
      properties:
        time:
          type: integer
          description: Time the event occurred, in seconds.  If NTP time was available when the event was logged, Epoch time will be used.  Otherwise, time since boot will be used
          example: 1709398094
        level:
          type: string
          description: Severity level for the event
          enum:
            - info
            - notify
            - error
            - unknown
          example: info
        text:
          type: string
          description: Descriptive text about the event
          example: Event log started

    errorLog:
      type: array
      items:
        $ref: '#/components/schemas/errorLogEntry'
    errorLogEntry:
      type: object
      properties:
        text:
          type: string
          description: Descriptive text about the event
          example: EEPROM Failure


    ##########################################################
    ## Versions                                             ##
    ##########################################################

    applicationVersion:
      type: string
      description: Software version
      example: '2024.2.1'

    productHex:
      type: string
      description: Hardware product hexadecimal, indicating the version of the firmware
      example: '0x8062305'

    applicationVersionInfo:
      type: object
      properties:
        application:
          $ref: '#/components/schemas/applicationVersion'
        product_hex:
          $ref: '#/components/schemas/productHex'

    uiVersionInfo:
      type: object
      properties:
        ui:
          $ref: '#/components/schemas/applicationVersion'


    ##########################################################
    ## Certificates                                         ##
    ##########################################################

    certificateListItem:
      type: object
      properties:
        file:
          type: string
          description: Certificate's filename
          example: mycert.pem
        size:
          type: integer
          description: Certificate's size in bytes
          example: 1410
    certificateList:
      type: array
      items:
        $ref: '#/components/schemas/certificateListItem'
    certificateContent:
      type: string
      example: '-----BEGIN CERTIFICATE----- MIID0zCCArugAwIBAgIQVmcdBOpPmUxvEIFHWdJ1lDANBgkqhkiG9w0BAQwFADB7 MQswCQYDVQQGEwJHQjEbMBkGA1UECAwSR3JlYXRlciBNYW5jaGVzdGVyMRAwDgYD VQQHDAdTYWxmb3JkMRowGAYDVQQKDBFDb21vZG8gQ0EgTGltaXRlZDEhMB8GA1UE AwwYQUFBIENlcnRpZmljYXRlIFNlcnZpY2VzMB4XDTE5MDMxMjAwMDAwMFoXDTI4 MTIzMTIzNTk1OVowgYgxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpOZXcgSmVyc2V5 MRQwEgYDVQQHEwtKZXJzZXkgQ2l0eTEeMBwGA1UEChMVVGhlIFVTRVJUUlVTVCBO ZXR3b3JrMS4wLAYDVQQDEyVVU0VSVHJ1c3QgRUNDIENlcnRpZmljYXRpb24gQXV0 aG9yaXR5MHYwEAYHKoZIzj0CAQYFK4EEACIDYgAEGqxUWqn5aCPnetUkb1PGWthL q8bVttHmc3Gu3ZzWDGH926CJA7gFFOxXzu5dP+Ihs8731Ip54KODfi2X0GHE8Znc JZFjq38wo7Rw4sehM5zzvy5cU7Ffs30yf4o043l5o4HyMIHvMB8GA1UdIwQYMBaA FKARCiM+lvEH7OKvKe+CpX/QMKS0MB0GA1UdDgQWBBQ64QmG1M8ZwpZ2dEl23OA1 xmNjmjAOBgNVHQ8BAf8EBAMCAYYwDwYDVR0TAQH/BAUwAwEB/zARBgNVHSAECjAI MAYGBFUdIAAwQwYDVR0fBDwwOjA4oDagNIYyaHR0cDovL2NybC5jb21vZG9jYS5j b20vQUFBQ2VydGlmaWNhdGVTZXJ2aWNlcy5jcmwwNAYIKwYBBQUHAQEEKDAmMCQG CCsGAQUFBzABhhhodHRwOi8vb2NzcC5jb21vZG9jYS5jb20wDQYJKoZIhvcNAQEM BQADggEBABns652JLCALBIAdGN5CmXKZFjK9Dpx1WywV4ilAbe7/ctvbq5AfjJXy ij0IckKJUAfiORVsAYfZFhr1wHUrxeZWEQff2Ji8fJ8ZOd+LygBkc7xGEJuTI42+ FsMuCIKchjN0djsoTI0DQoWz4rIjQtUfenVqGtF8qmchxDM6OW1TyaLtYiKou+JV bJlsQ2uRl9EMC5MCHdK8aXdJ5htN978UeAOwproLtOGFfy/cQjutdAFI3tZs4RmY CV4Ks2dH/hzg1cEo70qLRDEmBDeNiXQ2Lu+lIg+DdEmSx/cQwgwp+7e9un/jX9Wf 8qn0dNW44bOwgeThpWOjzOoEeJBuv/c= -----END CERTIFICATE-----'
    
    
    ##########################################################
    ## OTA Firmware                                         ##
    ##########################################################
    
    otaConfiguration:
      type: object
      properties:
        url:
          type: string
          format: url
          description: URL for the firmware update server
          example: http://www.somewhere.com/firmware.json
        certificate:
          type: string
          description: File name for the certificate that should be used when https is specified.  The existence of the certificate will not be checked until the OTA config is reloaded (typically on reboot)
          example: mycert.pem
      required:
        - url

    forceOTAConfiguration:
      type: object
      properties:
        url:
          type: string
          format: url
          description: URL for the binary file to flash
        certificate:
          type: string
          description: File name for the certificate that should be used when https is specified
          example: mycert.pem
      required:
        - url


    ##########################################################
    ## Controller                                           ##
    ##########################################################

      
    channel:
      type: object
      properties:
        channel:
          type: integer
          description: Physical channel within a port
          pattern: ^[1-3,6]$
          example: 2
          readOnly: true
        type:
          type: string
          description: Defines if the channel is normally open or normally closed
          enum:
            - NORMALLY_OPEN
            - NORMALLY_CLOSED
        long_change:
          type: boolean
          description: Indicates if long changes are enabled for this input
          default: true
        enabled:
          type: boolean
          description: Indicates if the channel is enabled
          default: true
      required:
        - type
    inputPort:
      type: object
      properties:
        name:
          type: string
          description: Human-friendly name of the input
          example: Kitchen Entryway
          maxLength: 20
        port: 
          type: integer
          description: Port number; Maximum is defined by the hardware capabilities
          minimum: 12
          readOnly: true

      required:
        - port
    outputPort:
      type: object
      properties:
        name:
          type: string
          description: Human-friendly name of the output
          example: Chandelier
          maxLength: 20
        port: 
          type: integer
          description: Port number; Maximum is defined by the hardware capabilities
          minimum: 1
        type:
          type: string
          description: Defines if the output is binary or variable
          enum:
            - BINARY
            - VARIABLE
        enabled:
          type: boolean
          description: Indicates if the output is enabled
          default: true
        
        state:
          type: string
          description: Current state of the output as a percentage.  If the `type` is `BINARY`, the value will be either 0 (off) or 100 (on)
          readOnly: true
          minimum: 0
          maximum: 100
      required:
        - port
        - type
    controller:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
          description: Unqiue ID assigned by the controller
          example: 9
        uuid:
          type: string
          description: Unique identifier for the device
          format: uuid
          minLength: 36
          maxLength: 36
        name:
          type: string
          description: Human-friendly name of the controller
          example: First floor
          maxLength: 20
      required:
        - uuid
        - id



    ##########################################################
    ## High Voltage                                         ##
    ##########################################################

    breaker:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
          description: Unqiue ID assigned by the controller
          example: 9
        name:
          type: string
          description: Human-friendly name of the breaker
          example: Panel A Breaker 2
          minLength: 1
          maxLength: 20
        amperage:
          $ref: '#/components/schemas/amperage_breaker'
    
    amperage_breaker:
      type: number
      format: double
      description: Maximum amperage rating for the breaker
      minimum: 0
      default: 0
      example: 20
    
    amperage_fixture:
      type: number
      format: double
      description: Maximum amperage draw of fixture(s) when powered on to the maximum potential
      minimum: 0
      default: 0
      example: 3.5
    
    relay_name:
      type: string
      description: Human-friendly name of the relay
      example: Circuit 12
      minLength: 1
      maxLength: 20
    
    relay_type:
      type: string
      description: Defines if the relay output to the fixture is binary or variable
      enum:
        - BINARY
        - VARIABLE
    
    relay_model:
      type: string
      description: Identifies the manufacturer and model of the relay
      example: DR2220D20U
      maxLength: 20

    relay:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
          description: Unqiue ID assigned by the controller
          example: 4
        name:
          $ref: '#/components/schemas/relay_name'
        amperage:
          $ref: '#/components/schemas/amperage_fixture'
        type:
          $ref: '#/components/schemas/relay_type'
        model:
          $ref: '#/components/schemas/relay_model'
      required:
        - name
        - type
    uniqueId:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
          description: Unqiue ID assigned by the controller
          example: 7
    configFile:
      type: object
      properties:
        controllers:
          type: array
          items: 
            $ref: '#/components/schemas/controller'
        breakers:
          type: array
          items: 
            $ref: '#/components/schemas/breaker'
       

##########################################################
##########################################################
## Examples                                             ##
##########################################################
##########################################################

  examples:
    emptyArray:
      value: []

    eventLog:
      value:
        - time: 1709398094
          level: info
          text: Event log started
        - time: 1709398150
          level: notify
          text: MQTT connected
        - time: 1709398228
          level: error
          text: MQTT disconnected
    
    errorLog:
      value:
        - text: MQTT disconnected
        - text: Ethernet disconnected
   
    ota_http:
      value:
        url: http://www.somewhere.com/firmware.json
    
    ota_https:
      value:
        url: https://www.somewhere.com/firmware.json
        certificate: mycert.pem